### ISSUE TITLE
SCSS boostrap path error when installing from npm

### ISSUE THREAD

**Issue by alanbernale** [themefisher/sleek-bootstrap#298]
When installing from npm, importing into project sass files and loading using webpack, it throws the following error:
`SassError: File to import not found or unreadable: ../node_modules/bootstrap/scss/bootstrap.scss. on line 3 of node_modules/sleek-dashboard/scss/sleek.scss`

Archivo sleek.scss en node_modules/sleek-dashboard/scss:
`@import "../node_modules/bootstrap/scss/bootstrap.scss";`

The error can be corrected by changing the path to:
`@import "~bootstrap/scss/bootstrap";`

**Comment by polynar** [comment]
#303

**Comment by iamabdus** [comment]
@alanbernale @polynar 
`@import "~bootstrap/scss/bootstrap"; ` does not work for direct use (git clone). Do you have any solution?

**Comment by polynar** [comment]
What do you mean direct use?
If someone doesn't want to use npm packages then use the compiled css in dist/assets folder and if you want to use scss and add customization to it use npm packages and use bootstrap.

Please tell me if I see the things wrong.

**Comment by iamabdus** [comment]
@polynar 
If you fork or git clone the Sleek and run it, `@import "~bootstrap/scss/bootstrap";` does not work.
